version: '2'
services:
  web:
    image: legerete/nginx-php7:develop
    container_name: porta-invest-crm-dev-web
    ports:
      - 40300:80
      - 40301:8006
    volumes:
      - .:/data:rw
      - ./www/:/data/www:rw
    depends_on:
      - mysql
    links:
      - mysql:mysql
    entrypoint: /data/start-server.sh
    restart: always
  mysql:
    image: mariadb
    container_name: porta-invest-crm-dev-db
    ports:
      - 3309:3306
    volumes:
      - ./mariadb:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: 08802e9a2ade49e40a55ff00faec
    restart: always
